name: Build Carbanak APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip autoconf libtool pkg-config zlib1g-dev \
            libncurses6-dev libncursesw6-dev libtinfo6 cmake \
            libffi-dev libssl-dev automake build-essential openjdk-17-jdk

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install "buildozer==1.5.0" "cython<3.0"

      - name: Build with Buildozer
        run: yes | buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_TEST_DOMAIN: 1
          BUILDOZER_WARN_ON_ROOT: 1

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Carbanak-App-Debug
          path: bin/*.apk
